#!/bin/sh
# install maven
branch=$(cat /var/easydeploy/share/.config/git_branch)
cat <<EOF
FROM neilellis/easydeploy-java-mvn-base
RUN git clone $2
RUN cd $1; (git checkout $branch || git checkout master)
RUN mvn install -Dmaven.test.skip
ADD /var/easydeploy/share/sync/global/.m2 /root/.m2
RUN export MAVEN_OPTS="-XX:OnOutOfMemoryError='kill -9 %p' -XX:+UseG1GC -Xmx1g -XX:MaxGCPauseMillis=50 \
     -Ddeploy.profile=$(cat /var/easydeploy/share/.config/deploy_env) \
     -Djava.awt.headless=true \
     -Dcom.sun.management.jmxremote \
     -Dcom.sun.management.jmxremote.port=9191 \
     -Dcom.sun.management.jmxremote.authenticate=false \
     -Dcom.sun.management.jmxremote.ssl=false \
     -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/local \
     -Djava.rmi.server.hostname=$(hostname -i)"
CMD mvn exec:java -pl $3
EOF

