#!/bin/bash -eu
alias kj='killall java'
alias dk='docker kill $(docker ps -q)'
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/ezbin:/root/bin
alias trun="tail -F /ezlog/run*"
alias tweave="tail -F /ezlog/weave*"
alias tconsul="tail -F /ezlog/consul*"
alias src="supervisorctl restart $(</ezshare/.config/component):"
alias health="/ezbin/health_check.sh"







